export const events = [
    {
        title: "Google I/O 2026",
        image: "/images/event1.png",
        slug: "google-io-2026",
        date: "May 12, 2026",
        time: "10:00 AM PST",
        location: "Mountain View, CA",
        description: "Catch up on the latest in AI, Mobile, and Web technologies from Google.",
    },
    {
        title: "React Conf 2026",
        image: "/images/event2.png",
        slug: "react-conf-2026",
        date: "June 25, 2026",
        time: "9:00 AM PST",
        location: "Henderson, NV",
        description: "The official React conference. Join us for two days of talks and workshops.",
    },
    {
        title: "AWS re:Invent 2026",
        image: "/images/event3.png",
        slug: "aws-reinvent-2026",
        date: "December 1, 2026",
        time: "8:00 AM PST",
        location: "Las Vegas, NV",
        description: "The most transformative event in tech. Discover the latest AWS innovations.",
    },
    {
        title: "Next.js Conf 2026",
        image: "/images/event4.png",
        slug: "nextjs-conf-2026",
        date: "October 24, 2026",
        time: "9:00 AM PST",
        location: "San Francisco, CA",
        description: "Learn about the latest Next.js features and best practices directly from the Vercel team.",
    },
    {
        title: "WWDC 2026",
        image: "/images/event5.png",
        slug: "wwdc-2026",
        date: "June 8, 2026",
        time: "10:00 AM PST",
        location: "Apple Park, Cupertino",
        description: "Apple's Worldwide Developers Conference. Get a first look at the next platforms.",
    },
    {
        title: "Git Merge 2026",
        image: "/images/event6.png",
        slug: "git-merge-2026",
        date: "July 15, 2026",
        time: "11:00 AM PST",
        location: "Los Angeles, CA",
        description: "The pre-eminent conference for the Git community, featuring expert talks and workshops.",
    }
];
